package org.omilab.robot.interfaces.mindbody;

public enum EnumMoveModelDirection {
	IDLE,
	WD4FORWARD, WD4BACKWARD, WD4LEFTTURN, WD4RIGHTTURN, 
	WD2LEFTSIDEFORWARD, WD2LEFTSIDEBACKWARD, WD2RIGHTSIDEFORWARD, WD2RIGHTSIDEBACKWARD, WD2FRONTFORWARD, WD2FRONTBACKWARD, WD2BACKBACKWARD, WD2BACKFORWARD, 
	WD1LEFTFRONTFORWARD, WD1RIGHTFRONTFORWARD, WD1LEFTBACKFORWARD, WD1RIGHTBACKFORWARD, 
	WD1LEFTFRONTBACKWARD, WD1RIGHTFRONTBACKWARD, WD1LEFTBACKBACKWARD, WD1RIGHTBACKBACKWARD, 
	WD4STOP,
	WD1LEFTFRONTSTOP, WD1LEFTBACKSTOP, WD1RIGHTFRONTSTOP, WD1RIGHTBACKSTOP
}
